import { useState } from "react";
import { Link, Navigate, useNavigate } from "react-router-dom";
import { FiEye, FiEyeOff, FiLock, FiMail, FiUser } from "react-icons/fi";
import { AssetsData } from "../assets/assets";
import api, { apiError } from "../api";

const Field = ({ label, icon, ...props }) => (
  <label className="block"><span className="mb-2 block text-sm font-semibold text-gray-700">{label}</span><span className="flex items-center rounded-lg border border-gray-200 bg-white px-3 shadow-sm focus-within:border-red-500 focus-within:ring-4 focus-within:ring-red-100">{icon}<input className="h-12 flex-1 border-0 bg-transparent px-3 text-sm outline-none" {...props} /></span></label>
);

export default function Auth({ mode }) {
  const register = mode === "register";
  const navigate = useNavigate();
  const [form, setForm] = useState({ name: "", email: "", password: "" });
  const [show, setShow] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (localStorage.getItem("harmain_token")) return <Navigate to="/" replace />;
  const set = (key) => (e) => setForm({ ...form, [key]: e.target.value });
  const submit = async (e) => { e.preventDefault(); setError(""); if (register && form.name.trim().length < 2) return setError("Enter your full name."); if (form.password.length < 8) return setError("Password must be at least 8 characters."); setBusy(true); try { const { data } = await api.post(`/auth/${register ? "register" : "login"}`, register ? form : { email: form.email, password: form.password }); localStorage.setItem("harmain_token", data.token); localStorage.setItem("harmain_user", JSON.stringify(data.user)); navigate("/", { replace: true }); } catch (err) { setError(apiError(err)); } finally { setBusy(false); } };
  return <section className="min-h-[calc(100vh-160px)] bg-red-50 px-4 py-12"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-2xl border border-red-100 bg-white shadow-xl md:grid-cols-2"><aside className="hidden bg-red-700 p-10 text-white md:block"><img src={AssetsData.logo} alt="Harmain Sharfain" className="h-20 w-20 rounded-full border-2 border-white bg-white object-cover" /><p className="mt-12 text-xs font-bold uppercase tracking-widest text-red-100">Harmain Sharfain</p><h1 className="mt-3 text-4xl font-bold leading-tight">Food made with care, ready when you are.</h1><p className="mt-5 text-sm leading-6 text-red-100">Your account makes ordering easier and keeps every visit personal.</p></aside><div className="p-7 sm:p-12"><Link to="/" className="text-sm font-bold text-red-700">Back to home</Link><p className="mt-10 text-xs font-bold uppercase tracking-widest text-red-700">Customer account</p><h2 className="mt-2 text-3xl font-bold text-gray-900">{register ? "Create your account" : "Welcome back"}</h2><p className="mt-2 text-sm text-gray-500">{register ? "Join Harmain Sharfain to order faster." : "Sign in to continue your experience."}</p>{error && <p className="mt-6 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<form className="mt-7 space-y-5" onSubmit={submit}>{register && <Field label="Full name" icon={<FiUser className="text-gray-400" />} value={form.name} onChange={set("name")} placeholder="Your full name" /> }<Field label="Email address" type="email" icon={<FiMail className="text-gray-400" />} value={form.email} onChange={set("email")} placeholder="name@example.com" /><label className="block"><span className="mb-2 block text-sm font-semibold text-gray-700">Password</span><span className="flex items-center rounded-lg border border-gray-200 bg-white px-3 shadow-sm focus-within:border-red-500 focus-within:ring-4 focus-within:ring-red-100"><FiLock className="text-gray-400" /><input className="h-12 flex-1 border-0 bg-transparent px-3 text-sm outline-none" type={show ? "text" : "password"} value={form.password} onChange={set("password")} placeholder="At least 8 characters" /><button type="button" className="text-gray-400 hover:text-red-700" onClick={() => setShow(!show)}>{show ? <FiEyeOff /> : <FiEye />}</button></span></label><button disabled={busy} className="h-12 w-full rounded-lg bg-red-700 text-sm font-bold text-white shadow-lg transition hover:bg-red-800 disabled:opacity-60">{busy ? "Please wait..." : register ? "Create account" : "Sign in"}</button></form><p className="mt-7 text-center text-sm text-gray-600">{register ? "Already have an account?" : "New to Harmain Sharfain?"} <Link className="font-bold text-red-700" to={register ? "/login" : "/register"}>{register ? "Sign in" : "Create account"}</Link></p></div></div></section>;
}
